import "./globals.css";
import Navbar from "./components/NavBar";
// import Footer from "./components/Footer";
import { Box } from "@mui/material";
import { ColorModeProvider } from "./context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body>
          <ColorModeProvider>
            <Navbar />
            <main style={{ padding: "1rem 0 3rem" }}>{children}</main>
            {/* <Footer /> */}
          </ColorModeProvider>
        </body>
      </html>
    </>
  );
}
