"use client";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import Navbar from "./components/NavBar";
// import { ColorModeProvider } from "./context";
import MyTheme from "./theme";
import ToggleColorMode from "./ToggleColorMode";
// import Footer from "./components/Footer";
import { Box } from "@mui/material";
import { ColorModeProvider } from "./context";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = MyTheme("light");

  return (
    <>
      <html lang="en">
        <body>
          <ColorModeProvider>
            {/* <ThemeProvider theme={theme}> */}
            <Navbar />
            <main style={{ padding: "1rem 0 3rem" }}>{children}</main>
            {/* <Footer /> */}
            {/* </ThemeProvider> */}
          </ColorModeProvider>
        </body>
      </html>
    </>
  );
}
